Repository wazo-platform/wazo-provd-plugins, pull requests merged in 2025-03, with the labels that each got.

#281 [WAZO-4055] yealink: use type 11 for online record funckeys
  plugins/wazo_yealink/common/common.py
  plugins/wazo_yealink/v73/plugin-info
  plugins/wazo_yealink/v80/plugin-info
  plugins/wazo_yealink/v81/plugin-info
  plugins/wazo_yealink/v82/common.py
  plugins/wazo_yealink/v82/plugin-info
  plugins/wazo_yealink/v83/common.py
  plugins/wazo_yealink/v83/plugin-info
  plugins/wazo_yealink/v84/common.py
  plugins/wazo_yealink/v84/plugin-info
  plugins/wazo_yealink/v85/common.py
  plugins/wazo_yealink/v85/plugin-info
  plugins/wazo_yealink/v86/common.py
  plugins/wazo_yealink/v86/plugin-info
Labels: mergeit

#283 YEALINK | v85 & v86 | Date Variable
  plugins/wazo_yealink/v85/plugin-info
  plugins/wazo_yealink/v85/templates/W75B.tpl
  plugins/wazo_yealink/v85/templates/W75DM.tpl
  plugins/wazo_yealink/v85/templates/W80B.tpl
  plugins/wazo_yealink/v85/templates/W80DM.tpl
  plugins/wazo_yealink/v85/templates/W90DM.tpl
  plugins/wazo_yealink/v85/templates/base.tpl
  plugins/wazo_yealink/v86/plugin-info
  plugins/wazo_yealink/v86/templates/base.tpl
Labels: bug, mergeit

#282 YEALINK | AX83H | Add device
  README.md
  plugins/wazo_yealink/v86/common.py
  plugins/wazo_yealink/v86/entry.py
  plugins/wazo_yealink/v86/pkgs/pkgs.db
  plugins/wazo_yealink/v86/plugin-info
  plugins/wazo_yealink/v86/templates/AX83H.tpl
Labels: enhancement, mergeit
