Repository wazo-platform/wazo-provd-plugins, pull requests merged in 2025-01, with the labels that each got.

#272 Yealink | T34W | Fix values
  plugins/wazo_yealink/v86/common.py
  plugins/wazo_yealink/v86/plugin-info
Labels: bug, mergeit

#269 Revert Mitel 6.4.0 language-pack removal
  plugins/wazo_aastra/v6_4_0_SP2/pkgs/pkgs.db
  plugins/wazo_aastra/v6_4_0_SP2/plugin-info
Labels: mergeit

#184 Gigaset N720, tune code tone
  plugins/wazo_gigaset/N720/plugin-info
  plugins/wazo_gigaset/N720/templates/base.tpl
  plugins/wazo_gigaset/common/common.py
Labels: mergeit

#194 polycom: add MAC address to User Agent
  plugins/wazo_polycom/common/templates/base.tpl
  plugins/wazo_polycom/v5_4_3/var/tftpboot/common.cfg
  plugins/wazo_polycom/v5_9_2/plugin-info
Labels: mergeit

#273 Yealink | W70B | Update Firmware
  plugins/wazo_yealink/v85/entry.py
  plugins/wazo_yealink/v85/pkgs/pkgs.db
  plugins/wazo_yealink/v85/plugin-info
Labels: enhancement, mergeit
